# Generated by Django 4.2.3 on 2023-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_roomreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='room_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='roomreservation',
            unique_together={('room_id', 'date')},
        ),
    ]
