# Generated by Django 4.2.3 on 2023-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0003_conferenceroom_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='room_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
