# Generated by Django 4.2.3 on 2023-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0004_alter_conferenceroom_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceroom',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
