# Generated by Django 4.2.3 on 2023-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0005_remove_conferenceroom_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='room_number',
            field=models.IntegerField(default=0),
        ),
    ]
