# Generated by Django 4.2.3 on 2023-07-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0006_conferenceroom_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceroom',
            name='room_number',
        ),
    ]
