# Generated by Django 4.2.3 on 2023-07-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0010_remove_conferenceroom_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='room_number',
            field=models.CharField(default='123', max_length=255),
        ),
    ]
