# Generated by Django 4.2.3 on 2023-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0011_conferenceroom_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='room_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
