# Generated by Django 4.2.3 on 2023-07-16 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0012_remove_conferenceroom_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceroom',
            name='room_number',
        ),
        migrations.AddField(
            model_name='conferenceroom',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='conferenceroom',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Rating must be at least 1.'), django.core.validators.MaxValueValidator(5, message='Rating must be 5 at most.')]),
        ),
        migrations.AlterField(
            model_name='conferenceroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
