# Generated by Django 4.2.3 on 2023-07-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0014_remove_conferenceroom_id_alter_conferenceroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceroom',
            name='rating',
        ),
    ]
